/**
 * CLI Configuration Module
 *
 * Manages configuration file loading, saving, and validation.
 * Supports .env files and .rwa-config.json for persistent settings.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';
import { logger } from './logger.js';

// ============================================
// TYPES
// ============================================

/**
 * CLI configuration structure
 */
export interface CLIConfig {
  // Network
  network?: 'mainnet' | 'testnet';
  l1RpcUrl?: string;
  l2RpcUrl?: string;

  // Wallet
  privateKey?: string;

  // Gas Module
  gasBufferPercentage?: number;

  // Indexer Module
  indexerDbPath?: string;
  indexerPollInterval?: number;

  // CLI Settings
  debug?: boolean;
  quiet?: boolean;
  outputFormat?: 'text' | 'json';
}

/**
 * Config file paths
 */
export interface ConfigPaths {
  envFile: string;
  configFile: string;
}

// ============================================
// CONSTANTS
// ============================================

const DEFAULT_CONFIG_FILENAME = '.rwa-config.json';
const DEFAULT_ENV_FILENAME = '.env';

const DEFAULT_CONFIG: CLIConfig = {
  network: 'testnet',
  l1RpcUrl: 'https://eth-sepolia.public.blastapi.io',
  l2RpcUrl: 'https://rpc.sepolia.mantle.xyz',
  gasBufferPercentage: 10,
  indexerDbPath: './.rwa-data/indexer.db',
  indexerPollInterval: 12000,
  debug: false,
  quiet: false,
  outputFormat: 'text',
};

// Keys that can be set via CLI config commands
const ALLOWED_CONFIG_KEYS: (keyof CLIConfig)[] = [
  'network',
  'l1RpcUrl',
  'l2RpcUrl',
  'gasBufferPercentage',
  'indexerDbPath',
  'indexerPollInterval',
  'debug',
  'quiet',
  'outputFormat',
];

// Sensitive keys that should not be printed
const SENSITIVE_KEYS: (keyof CLIConfig)[] = ['privateKey'];

// ============================================
// FILE PATH UTILITIES
// ============================================

/**
 * Find the project root (directory containing package.json)
 */
function findProjectRoot(startDir: string = process.cwd()): string {
  let dir = startDir;
  while (dir !== path.dirname(dir)) {
    if (fs.existsSync(path.join(dir, 'package.json'))) {
      return dir;
    }
    dir = path.dirname(dir);
  }
  return startDir;
}

/**
 * Get config file paths
 */
export function getConfigPaths(customDir?: string): ConfigPaths {
  const baseDir = customDir ?? process.cwd();
  return {
    envFile: path.join(baseDir, DEFAULT_ENV_FILENAME),
    configFile: path.join(baseDir, DEFAULT_CONFIG_FILENAME),
  };
}

// ============================================
// CONFIG FILE OPERATIONS
// ============================================

/**
 * Load .env file if it exists
 */
function loadEnvFile(envPath: string): Record<string, string> {
  if (!fs.existsSync(envPath)) {
    return {};
  }

  try {
    const result = dotenv.config({ path: envPath });
    if (result.error) {
      logger.warn(`Failed to parse .env file: ${result.error.message}`);
      return {};
    }
    return result.parsed ?? {};
  } catch (error) {
    logger.warn(`Error reading .env file: ${(error as Error).message}`);
    return {};
  }
}

/**
 * Load .rwa-config.json if it exists
 */
function loadConfigFile(configPath: string): Partial<CLIConfig> {
  if (!fs.existsSync(configPath)) {
    return {};
  }

  try {
    const content = fs.readFileSync(configPath, 'utf-8');
    const parsed = JSON.parse(content);
    return parsed as Partial<CLIConfig>;
  } catch (error) {
    logger.warn(`Failed to parse config file: ${(error as Error).message}`);
    return {};
  }
}

/**
 * Save configuration to .rwa-config.json
 */
export function saveConfigFile(config: Partial<CLIConfig>, configPath?: string): void {
  const paths = getConfigPaths();
  const targetPath = configPath ?? paths.configFile;

  // Filter out sensitive keys before saving
  const safeConfig: Partial<CLIConfig> = {};
  for (const key of Object.keys(config) as (keyof CLIConfig)[]) {
    if (!SENSITIVE_KEYS.includes(key)) {
      (safeConfig as Record<string, unknown>)[key] = config[key];
    }
  }

  try {
    const content = JSON.stringify(safeConfig, null, 2);
    fs.writeFileSync(targetPath, content, 'utf-8');
    logger.debug(`Config saved to ${targetPath}`);
  } catch (error) {
    throw new Error(`Failed to save config file: ${(error as Error).message}`);
  }
}

/**
 * Create default .env file template
 */
export function createEnvTemplate(envPath?: string): void {
  const paths = getConfigPaths();
  const targetPath = envPath ?? paths.envFile;

  const template = `# RWA Lifecycle SDK Configuration
# Generated by rwa-cli init

# Network (mainnet or testnet)
RWA_NETWORK=testnet

# RPC URLs
RWA_L1_RPC_URL=https://eth-sepolia.public.blastapi.io
RWA_L2_RPC_URL=https://rpc.sepolia.mantle.xyz

# Wallet (KEEP SECRET - never commit this!)
# RWA_PRIVATE_KEY=0x...

# Gas Settings
RWA_GAS_BUFFER_PERCENTAGE=10

# Indexer Settings
RWA_INDEXER_DB_PATH=./.rwa-data/indexer.db
RWA_INDEXER_POLL_INTERVAL=12000
`;

  try {
    // Don't overwrite if exists
    if (fs.existsSync(targetPath)) {
      throw new Error('.env file already exists. Remove it first or use --force.');
    }
    fs.writeFileSync(targetPath, template, 'utf-8');
    logger.success(`Created ${targetPath}`);
  } catch (error) {
    throw new Error(`Failed to create .env file: ${(error as Error).message}`);
  }
}

/**
 * Create default .rwa-config.json
 */
export function createConfigTemplate(configPath?: string): void {
  const paths = getConfigPaths();
  const targetPath = configPath ?? paths.configFile;

  const template: Partial<CLIConfig> = {
    network: 'testnet',
    gasBufferPercentage: 10,
    indexerDbPath: './.rwa-data/indexer.db',
    indexerPollInterval: 12000,
    outputFormat: 'text',
  };

  try {
    // Don't overwrite if exists
    if (fs.existsSync(targetPath)) {
      throw new Error('.rwa-config.json already exists. Remove it first or use --force.');
    }
    const content = JSON.stringify(template, null, 2);
    fs.writeFileSync(targetPath, content, 'utf-8');
    logger.success(`Created ${targetPath}`);
  } catch (error) {
    throw new Error(`Failed to create config file: ${(error as Error).message}`);
  }
}

// ============================================
// CONFIG LOADING & MERGING
// ============================================

/**
 * Convert environment variables to CLIConfig
 */
function envToConfig(env: Record<string, string | undefined>): Partial<CLIConfig> {
  const config: Partial<CLIConfig> = {};

  if (env.RWA_NETWORK) {
    config.network = env.RWA_NETWORK as 'mainnet' | 'testnet';
  }
  if (env.RWA_L1_RPC_URL) {
    config.l1RpcUrl = env.RWA_L1_RPC_URL;
  }
  if (env.RWA_L2_RPC_URL) {
    config.l2RpcUrl = env.RWA_L2_RPC_URL;
  }
  if (env.RWA_PRIVATE_KEY) {
    config.privateKey = env.RWA_PRIVATE_KEY;
  }
  if (env.RWA_GAS_BUFFER_PERCENTAGE) {
    config.gasBufferPercentage = parseInt(env.RWA_GAS_BUFFER_PERCENTAGE, 10);
  }
  if (env.RWA_INDEXER_DB_PATH) {
    config.indexerDbPath = env.RWA_INDEXER_DB_PATH;
  }
  if (env.RWA_INDEXER_POLL_INTERVAL) {
    config.indexerPollInterval = parseInt(env.RWA_INDEXER_POLL_INTERVAL, 10);
  }

  return config;
}

/**
 * Load and merge all configuration sources
 *
 * Priority (highest to lowest):
 * 1. CLI flags (passed as overrides)
 * 2. Environment variables
 * 3. .env file
 * 4. .rwa-config.json
 * 5. Default values
 */
export function loadConfig(overrides?: Partial<CLIConfig>): CLIConfig {
  const paths = getConfigPaths();

  // Load from files
  const envFileConfig = envToConfig(loadEnvFile(paths.envFile));
  const jsonConfig = loadConfigFile(paths.configFile);

  // Load from current environment (may be set outside .env)
  const envConfig = envToConfig(process.env);

  // Merge all sources
  const merged: CLIConfig = {
    ...DEFAULT_CONFIG,
    ...jsonConfig,
    ...envFileConfig,
    ...envConfig,
    ...overrides,
  };

  return merged;
}

// ============================================
// CONFIG GET/SET OPERATIONS
// ============================================

/**
 * Get a single config value
 */
export function getConfigValue(key: string): unknown {
  const config = loadConfig();

  if (!(key in config)) {
    throw new Error(`Unknown config key: ${key}`);
  }

  if (SENSITIVE_KEYS.includes(key as keyof CLIConfig)) {
    const value = config[key as keyof CLIConfig];
    return value ? '***' : undefined;
  }

  return config[key as keyof CLIConfig];
}

/**
 * Set a config value (saved to .rwa-config.json)
 */
export function setConfigValue(key: string, value: string): void {
  if (!ALLOWED_CONFIG_KEYS.includes(key as keyof CLIConfig)) {
    throw new Error(
      `Cannot set '${key}'. Allowed keys: ${ALLOWED_CONFIG_KEYS.join(', ')}`
    );
  }

  const paths = getConfigPaths();
  const currentConfig = loadConfigFile(paths.configFile);

  // Parse value based on expected type
  let parsedValue: string | number | boolean = value;

  if (key === 'gasBufferPercentage' || key === 'indexerPollInterval') {
    parsedValue = parseInt(value, 10);
    if (isNaN(parsedValue)) {
      throw new Error(`${key} must be a number`);
    }
  } else if (key === 'debug' || key === 'quiet') {
    parsedValue = value === 'true' || value === '1';
  } else if (key === 'network') {
    if (value !== 'mainnet' && value !== 'testnet') {
      throw new Error('network must be "mainnet" or "testnet"');
    }
  } else if (key === 'outputFormat') {
    if (value !== 'text' && value !== 'json') {
      throw new Error('outputFormat must be "text" or "json"');
    }
  }

  // Update and save
  (currentConfig as Record<string, unknown>)[key] = parsedValue;
  saveConfigFile(currentConfig, paths.configFile);
}

/**
 * Get all config values (for display)
 */
export function getAllConfig(): Record<string, unknown> {
  const config = loadConfig();
  const result: Record<string, unknown> = {};

  for (const key of Object.keys(config) as (keyof CLIConfig)[]) {
    if (SENSITIVE_KEYS.includes(key)) {
      result[key] = config[key] ? '***' : undefined;
    } else {
      result[key] = config[key];
    }
  }

  return result;
}

/**
 * Validate configuration for SDK initialization
 */
export function validateConfig(config: CLIConfig): string[] {
  const errors: string[] = [];

  if (!config.l1RpcUrl) {
    errors.push('L1 RPC URL is required');
  }
  if (!config.l2RpcUrl) {
    errors.push('L2 RPC URL is required');
  }
  if (config.network && config.network !== 'mainnet' && config.network !== 'testnet') {
    errors.push('network must be "mainnet" or "testnet"');
  }
  if (config.gasBufferPercentage !== undefined) {
    if (config.gasBufferPercentage < 0 || config.gasBufferPercentage > 100) {
      errors.push('gasBufferPercentage must be between 0 and 100');
    }
  }
  if (config.indexerPollInterval !== undefined) {
    if (config.indexerPollInterval < 1000) {
      errors.push('indexerPollInterval must be at least 1000ms');
    }
  }

  return errors;
}

/**
 * Check if configuration files exist
 */
export function configFilesExist(): { envExists: boolean; configExists: boolean } {
  const paths = getConfigPaths();
  return {
    envExists: fs.existsSync(paths.envFile),
    configExists: fs.existsSync(paths.configFile),
  };
}
